FROM confluentinc/cp-kafka-connect:7.7.1

# Install Debezium MySQL Connector
RUN confluent-hub install --no-prompt debezium/debezium-connector-mysql:2.4.2

# Copy the connector configuration file
COPY docker/connectors/mysql-connector.json /etc/kafka/connect/connectors/

# Script to create the connector
COPY docker/connectors/startup.sh /etc/kafka/connect/startup.sh

USER root
RUN chmod +x /etc/kafka/connect/startup.sh

ENTRYPOINT ["/etc/kafka/connect/startup.sh"]